# Generated by Django 4.2.30 on 2026-07-27 20:19

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                CREATE VIRTUAL TABLE entry_fts USING fts5(
                    transcript,
                    content='journal_entry',
                    content_rowid='id'
                );

                -- Triggers to keep the FTS index in sync with the journal_entry table
                CREATE TRIGGER entry_ai AFTER INSERT ON journal_entry BEGIN
                    INSERT INTO entry_fts(rowid, transcript) VALUES (new.id, new.transcript);
                END;

                CREATE TRIGGER entry_ad AFTER DELETE ON journal_entry BEGIN
                    INSERT INTO entry_fts(entry_fts, rowid, transcript) VALUES('delete', old.id, old.transcript);
                END;

                CREATE TRIGGER entry_au AFTER UPDATE ON journal_entry BEGIN
                    INSERT INTO entry_fts(entry_fts, rowid, transcript) VALUES('delete', old.id, old.transcript);
                    INSERT INTO entry_fts(rowid, transcript) VALUES (new.id, new.transcript);
                END;
            ''',
            reverse_sql='''
                DROP TRIGGER IF EXISTS entry_au;
                DROP TRIGGER IF EXISTS entry_ad;
                DROP TRIGGER IF EXISTS entry_ai;
                DROP TABLE IF EXISTS entry_fts;
            '''
        )
    ]
